project:
  type: book
  output-dir: docs

#bibliography: bibliog.bib
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
lang: pt-BR
book:
  page-navigation: true
  reader-mode: true
  cover-image: hardcover.png
  favicon: favicon.ico
  title: "Probabilidade & Estatística"
  subtitle: "Um curso para o PROFMAT"
  author: "Ben Dêivide de O. Batista </br> Andre F. Barboza </br> Francismara F. Guerra </br> Isabella S. Cruz </br> Jomara S. Pereira </br> José M. dos Santos </br> Leonardo B. da Silva </br> Luciano R. Coelho </br> Tatiana M. S. Brandão"
  date: ""
  page-footer:
    left: |
      Probabilidade & Estatística: Um curso para o PROFMAT foi escrito por  <a href="https://bendeivide.github.io/">Ben Dêivide de O. Batista</a>, Andre F. Barboza, Francismara F. Guerra, Isabella S. Cruz, Jomara S. Pereira, José M. dos Santos, Leonardo B. da Silva, Luciano R. Coelho e Tatiana M. S. Brandão. 
    right: |
      Esse livro foi desenvolvido com o <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - references.qmd

#https://quarto.org/docs/output-formats/html-themes.html
format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt
